3-я задача и на половину 4-я
js-tasks-ru/vue-20230120_for-sna pull request #3
Opened 2023-02-07 16:12 UTC by NatallD

2023-02-07 16:13 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-02-08 19:36 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-02-08 21:58 UTC, ShGKme requested changes
В `01-basics/03-MarkedList` вычисляемое свойство используется некорректно. В нём должно вычисляться значение этого свойства, а не меняться другие данные. Не должно быть побочных эффектов. 

Обратите внимание также на другие комментарии и общее форматирование и стиль кода. Такие имена переменных и свойств, как `f` и `t` не описывают значение этих свойств, а отступы должны отражать реальную вложенность блоков.

2023-02-08 21:58 UTC, ShGKme commented on 01-basics/03-MarkedList/index.html
> +			<div v-else>{{ item.name }}</div>
Когда по условию меняется лишь небольшая часть узла (например, содержимое, атрибут, класс), лучше в шаблоне динамически описывать именно эту вариативную часть.

С `v-if` получается копирование целиком узла, это дублирование всего кода узла.

Для классов во Vue есть даже специальный синтаксис с объектом, который делает удобным привязку классов по условию: https://vuejs.org/guide/essentials/class-and-style.html#binding-to-objects

2023-02-08 21:58 UTC, ShGKme commented on 01-basics/03-MarkedList/script.js
> +		}
Метод `map` здесь используется некорректно. map - это метод отображения. Он создаёт новый массив из старого, путём преобразования элемента старого массива в соответствующий элемент нового. Здесь же `map` используется, как просто цикл для перебора элементов и их изменения в процессе перебора, а в итоге возвращает массив из `undefined`.

2023-02-08 21:58 UTC, ShGKme commented on 01-basics/03-MarkedList/script.js
> +		}
В вычисляемом свойстве свойстве не должно быть побочных эффектов. Оно должно описываться функцией, которая возвращает значение - вычисленное значение свойства. Так и получается вычисляемое свойство. Это вычисляемое свойство в процессе вычисления изменяет состояние приложения. Так как мы сами не вызываем перевычисление вычисляемого свойства (за это отвечает Vue), мы не контролируем, как и когда оно будет менять данные приложения.

2023-02-08 21:58 UTC, ShGKme commented on 01-basics/04-MeetupTitle/index.html
>          <hr />
Во Vue приложение управляется данными. Для установки выбранной изначально радиокнопки требуется не привязывать ей явно `checked` через `:checked="item == 1"`, а определять начальное значение того свойства, которое и определяет выбранную радиокнопку. Это делает `v-model="selIdMeetup"`, устанавливая всё то же свойство `checked`. Иначе может появиться два источника определения `checked`, а в приложении изначально быть некорректное состояние. По шаблону выбрана одна радиокнопка, а по данным - может быть другая.

2023-02-08 21:58 UTC, ShGKme commented on 01-basics/04-MeetupTitle/index.html
>          <hr />
Вместо массива `[1,2,3,4,5]` в `v-for` для перебора значений от 1 до 5, можно использовать просто `v-for="item in 5"`

2023-02-08 21:58 UTC, ShGKme commented on 01-basics/04-MeetupTitle/script.js
> +			this.selIdMeetup =  newValue;
`newValue` - это новое значение отслеживаемого свойства `selIdMeetup`.

`this.selIdMeetup =  newValue;` - присваивает в свойство его же значение.

2023-02-10 15:07 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-02-10 18:17 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-02-10 18:18 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-02-10 18:20 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-02-10 19:22 UTC, ShGKme requested changes
В `01-basics/03-MarkedList` осталось небольшое изменение по комментарию, остальные задачи приняты

2023-02-10 19:22 UTC, ShGKme commented on 01-basics/03-MarkedList/script.js
> +				return newEList;
Здесь лучше подойдёт метод `map`.

2023-02-10 19:22 UTC, ShGKme commented on 01-basics/03-MarkedList/index.html
> +	      </template>
Здесь небольшая проблемка осталась. Для добавления класса по условию требуется использовать `v-bind` с синтаксисом привязки классов объектом.

Это мелочь, но это важная и часто используемая возможность Vue, важно с ней тоже разобраться.

https://vuejs.org/guide/essentials/class-and-style.html#binding-to-objects

2023-02-11 14:36 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-02-11 14:43 UTC, NatallD commented on 01-basics/03-MarkedList/index.html
> +	      </template>
Верно! Упустила этот момент и тогда не ненужно будет плодить <li>

2023-02-11 14:46 UTC, NatallD commented on 01-basics/03-MarkedList/script.js
> +				return newEList;
Вы раннее указали, что использовать map неверно.  В последнем варианте я сделала с использованием map, но учла чтоб массив объектов не был перезаписан.

2023-02-11 15:05 UTC, ShGKme commented on 01-basics/03-MarkedList/script.js
> +				return newEList;
Я писал что "Метод map здесь используется некорректно". Не сам факт использования map некорректен, а именно то использование `map` с перспективы JS было некорректным.

Там вы использовали метод создания массива отображением `map` как цикл, в котором мутировали массив. Это неправильное использование `map`.

Сейчас вы создаёте создаёте массив, фактически делая его отображение. Но уже без метода `map`, а с простым циклом.

Лучший вариант - это создать новый массив отображением методом `map`.

2023-02-11 15:33 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-02-11 15:34 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-02-11 15:50 UTC, ShGKme approved these changes
Все задачи приняты

2023-02-11 15:50 UTC, ShGKme commented on 01-basics/03-MarkedList/index.html
> +	      </template>
Элемент `<template>` в шаблоне нужен, когда требуется для директив `v-if` или `v-for` обернуть несколько узлов сразу.

Если узел один, то директиву можно использовать непосредственно на нём без лишних обёрток.

2023-02-11 15:50 UTC, merged